USE [Quiz]
GO

/****** Object:  Table [dbo].[Choice]    Script Date: 5/11/2020 10:10:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Choice](
	[CHOICE_ID] [int] IDENTITY(6000,1) NOT NULL,
	[CHOICE_STRING] [varchar](255) NOT NULL,
	[IF_CORRECT] [bit] NOT NULL,
	[QUESTION_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CHOICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Choice]  WITH CHECK ADD  CONSTRAINT [Choice_Question_QUESTION_ID_fk] FOREIGN KEY([QUESTION_ID])
REFERENCES [dbo].[Question] ([QUESTION_ID])
GO

ALTER TABLE [dbo].[Choice] CHECK CONSTRAINT [Choice_Question_QUESTION_ID_fk]
GO


USE [Quiz]
GO

/****** Object:  Table [dbo].[Feedback]    Script Date: 5/11/2020 10:10:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Feedback](
	[FEEDBACK_ID] [int] IDENTITY(5000,1) NOT NULL,
	[RATING] [int] NULL,
	[FEEDBACK_STRING] [varchar](30) NULL,
	[QUIZ_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FEEDBACK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Quiz]
GO

/****** Object:  Table [dbo].[Question]    Script Date: 5/11/2020 10:10:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Question](
	[QUESTION_ID] [int] IDENTITY(3000,1) NOT NULL,
	[QUESTION_TYPE] [varchar](5) NOT NULL,
	[QUESTION_STRING] [varchar](255) NOT NULL,
	[QUIZ_ID] [int] NOT NULL,
	[MODIFIED_TIME] [varchar](100) NULL,
	[STATUS] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[QUESTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Question]  WITH CHECK ADD  CONSTRAINT [Question_QuizInfo_QUIZ_ID_fk] FOREIGN KEY([QUIZ_ID])
REFERENCES [dbo].[QuizInfo] ([QUIZ_ID])
GO

ALTER TABLE [dbo].[Question] CHECK CONSTRAINT [Question_QuizInfo_QUIZ_ID_fk]
GO

USE [Quiz]
GO

/****** Object:  Table [dbo].[QuizInfo]    Script Date: 5/11/2020 10:11:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QuizInfo](
	[QUIZ_ID] [int] IDENTITY(2000,1) NOT NULL,
	[QUIZ_NAME] [varchar](30) NOT NULL,
	[QUIZ_IMG] [varchar](30) NOT NULL,
	[Quiz_DESC] [varchar](500) NOT NULL,
	[QUIZ_COUNT] [int] NOT NULL,
	[MODIFIED_TIME] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[QUIZ_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Quiz]
GO

/****** Object:  Table [dbo].[UserAnswer]    Script Date: 5/11/2020 10:11:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserAnswer](
	[ANSWER_ID] [int] IDENTITY(7000,1) NOT NULL,
	[ANSWER_STRING] [varchar](255) NOT NULL,
	[IF_CORRECT] [bit] NOT NULL,
	[QUESTION_ID] [int] NOT NULL,
	[SUBMISSION_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ANSWER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserAnswer]  WITH CHECK ADD  CONSTRAINT [UserAnswer_Question_QUESTION_ID_fk] FOREIGN KEY([QUESTION_ID])
REFERENCES [dbo].[Question] ([QUESTION_ID])
GO

ALTER TABLE [dbo].[UserAnswer] CHECK CONSTRAINT [UserAnswer_Question_QUESTION_ID_fk]
GO

ALTER TABLE [dbo].[UserAnswer]  WITH CHECK ADD  CONSTRAINT [UserAnswer_UserSubmission_SUBMISSION_ID_fk] FOREIGN KEY([SUBMISSION_ID])
REFERENCES [dbo].[UserSubmission] ([SUBMISSION_ID])
GO

ALTER TABLE [dbo].[UserAnswer] CHECK CONSTRAINT [UserAnswer_UserSubmission_SUBMISSION_ID_fk]
GO

USE [Quiz]
GO

/****** Object:  Table [dbo].[UserGroup]    Script Date: 5/11/2020 10:11:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserGroup](
	[GROUP_ID] [int] IDENTITY(7000,1) NOT NULL,
	[GROUP_NAME] [varchar](30) NULL,
	[GROUP_DESC] [varchar](30) NULL,
	[GROUP_LEVEL] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Quiz]
GO

/****** Object:  Table [dbo].[UserInfo]    Script Date: 5/11/2020 10:11:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserInfo](
	[USER_ID] [int] IDENTITY(1000,1) NOT NULL,
	[USER_NAME] [varchar](30) NULL,
	[USER_PASSWORD] [varchar](30) NULL,
	[USER_STATUS] [int] NOT NULL,
	[FIRST_NAME] [varchar](30) NULL,
	[LAST_NAME] [varchar](30) NULL,
	[EMAIL] [varchar](30) NULL,
	[BIRTH_DATE] [varchar](30) NULL,
	[GROUP_ID] [int] NOT NULL,
	[ADDRESS] [varchar](100) NULL,
	[PHONE] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Quiz]
GO

/****** Object:  Table [dbo].[UserSubmission]    Script Date: 5/11/2020 10:11:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserSubmission](
	[SUBMISSION_ID] [int] IDENTITY(4000,1) NOT NULL,
	[START_TIME] [varchar](100) NOT NULL,
	[END_TIME] [varchar](100) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[CORRECT_COUNT] [int] NULL,
	[TOTAL_COUNT] [int] NULL,
	[QUIZ_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SUBMISSION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserSubmission]  WITH CHECK ADD  CONSTRAINT [UserSubmission_QuizInfo_QUIZ_ID_fk] FOREIGN KEY([QUIZ_ID])
REFERENCES [dbo].[QuizInfo] ([QUIZ_ID])
GO

ALTER TABLE [dbo].[UserSubmission] CHECK CONSTRAINT [UserSubmission_QuizInfo_QUIZ_ID_fk]
GO

ALTER TABLE [dbo].[UserSubmission]  WITH CHECK ADD  CONSTRAINT [UserSubmission_UserInfo_USER_ID_fk] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[UserInfo] ([USER_ID])
GO

ALTER TABLE [dbo].[UserSubmission] CHECK CONSTRAINT [UserSubmission_UserInfo_USER_ID_fk]
GO

